[package]
name = "test-helpers"
edition = "2021"
version.workspace = true

[dependencies]
configuration = { path = "../configuration" }
mongodb-support = { path = "../mongodb-support" }

enum-iterator = "^2.0.0"
mongodb = "2.8"
proptest = "1"

