mod collection;
mod database;
pub mod sanitize;
mod selection;

#[cfg(any(test, feature = "test-helpers"))]
pub mod test_helpers;

pub use self::{
    collection::CollectionTrait, database::DatabaseTrait, selection::selection_from_query_request,
};

// MockCollectionTrait is generated by automock when the test flag is active.
#[cfg(any(test, feature = "test-helpers"))]
pub use self::collection::MockCollectionTrait;

// MockDatabase is generated by automock when the test flag is active.
#[cfg(any(test, feature = "test-helpers"))]
pub use self::database::MockDatabaseTrait;
