/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AnotherColumnComparison {
    #[serde(rename = "column")]
    pub column: Box<crate::ComparisonColumn>,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl AnotherColumnComparison {
    pub fn new(column: crate::ComparisonColumn, r#type: RHashType) -> AnotherColumnComparison {
        AnotherColumnComparison {
            column: Box::new(column),
            r#type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "column")]
    Column,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Column
    }
}
