/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplyBinaryArrayComparisonOperator {
    #[serde(rename = "column")]
    pub column: crate::ComparisonColumn,
    #[serde(rename = "operator")]
    pub operator: crate::BinaryArrayComparisonOperator,
    #[serde(rename = "type")]
    pub r#type: RHashType,
    #[serde(rename = "value_type")]
    pub value_type: String,
    #[serde(rename = "values")]
    pub values: Vec<serde_json::Value>,
}

impl ApplyBinaryArrayComparisonOperator {
    pub fn new(
        column: crate::ComparisonColumn,
        operator: crate::BinaryArrayComparisonOperator,
        r#type: RHashType,
        value_type: String,
        values: Vec<serde_json::Value>,
    ) -> ApplyBinaryArrayComparisonOperator {
        ApplyBinaryArrayComparisonOperator {
            column,
            operator,
            r#type,
            value_type,
            values,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "binary_arr_op")]
    BinaryArrOp,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::BinaryArrOp
    }
}

#[cfg(test)]
mod test {
    use mongodb::bson::{bson, from_bson};

    use crate::comparison_column::ColumnSelector;
    use crate::BinaryArrayComparisonOperator;
    use crate::ComparisonColumn;

    use super::ApplyBinaryArrayComparisonOperator;
    use super::RHashType;

    #[test]
    fn parses_rhash_type() -> Result<(), anyhow::Error> {
        let input = bson!("binary_arr_op");
        assert_eq!(from_bson::<RHashType>(input)?, RHashType::BinaryArrOp);
        Ok(())
    }

    #[test]
    fn parses_apply_binary_comparison_operator() -> Result<(), anyhow::Error> {
        let input = bson!({
            "type": "binary_arr_op",
            "column": {"column_type": "string", "name": "title"},
            "operator": "in",
            "value_type": "string",
            "values": ["One", "Two"]
        });
        assert_eq!(
            from_bson::<ApplyBinaryArrayComparisonOperator>(input)?,
            ApplyBinaryArrayComparisonOperator {
                r#type: RHashType::BinaryArrOp,
                column: ComparisonColumn {
                    column_type: "string".to_owned(),
                    name: ColumnSelector::new("title".to_owned()),
                    path: None
                },
                operator: BinaryArrayComparisonOperator::In,
                value_type: "string".to_owned(),
                values: vec!["One".into(), "Two".into()]
            }
        );
        Ok(())
    }
}
