/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ArrayRelationInsertSchema {
    /// The name of the array relationship over which the related rows must be inserted
    #[serde(rename = "relationship")]
    pub relationship: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl ArrayRelationInsertSchema {
    pub fn new(relationship: String, r#type: RHashType) -> ArrayRelationInsertSchema {
        ArrayRelationInsertSchema {
            relationship,
            r#type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "array_relation")]
    ArrayRelation,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::ArrayRelation
    }
}
