/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CapabilitiesResponse {
    #[serde(rename = "capabilities")]
    pub capabilities: Box<crate::Capabilities>,
    #[serde(rename = "config_schemas")]
    pub config_schemas: Box<crate::ConfigSchemaResponse>,
    #[serde(rename = "display_name", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "release_name", skip_serializing_if = "Option::is_none")]
    pub release_name: Option<String>,
}

impl CapabilitiesResponse {
    pub fn new(
        capabilities: crate::Capabilities,
        config_schemas: crate::ConfigSchemaResponse,
    ) -> CapabilitiesResponse {
        CapabilitiesResponse {
            capabilities: Box::new(capabilities),
            config_schemas: Box::new(config_schemas),
            display_name: None,
            release_name: None,
        }
    }
}
