/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ColumnValueGenerationStrategy {
    #[serde(rename = "auto_increment")]
    AutoIncrement {},
    #[serde(rename = "default_value")]
    DefaultValue {},
    #[serde(rename = "unique_identifier")]
    UniqueIdentifier {},
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "unique_identifier")]
    UniqueIdentifier,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::UniqueIdentifier
    }
}
