/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ColumnNullability {
    #[serde(rename = "only_nullable")]
    OnlyNullable,
    #[serde(rename = "nullable_and_non_nullable")]
    NullableAndNonNullable,
}

impl ToString for ColumnNullability {
    fn to_string(&self) -> String {
        match self {
            Self::OnlyNullable => String::from("only_nullable"),
            Self::NullableAndNonNullable => String::from("nullable_and_non_nullable"),
        }
    }
}

impl Default for ColumnNullability {
    fn default() -> ColumnNullability {
        Self::OnlyNullable
    }
}
