/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ComparisonCapabilities {
    #[serde(
        rename = "subquery",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub subquery: Option<Option<Box<crate::SubqueryComparisonCapabilities>>>,
}

impl ComparisonCapabilities {
    pub fn new() -> ComparisonCapabilities {
        ComparisonCapabilities { subquery: None }
    }
}
