/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomUpdateColumnOperatorRowUpdate {
    /// The name of the column in the row
    #[serde(rename = "column")]
    pub column: String,
    #[serde(rename = "operator_name")]
    pub operator_name: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The value to use with the column operator
    #[serde(rename = "value")]
    pub value: ::std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "value_type")]
    pub value_type: String,
}

impl CustomUpdateColumnOperatorRowUpdate {
    pub fn new(
        column: String,
        operator_name: String,
        r#type: RHashType,
        value: ::std::collections::HashMap<String, serde_json::Value>,
        value_type: String,
    ) -> CustomUpdateColumnOperatorRowUpdate {
        CustomUpdateColumnOperatorRowUpdate {
            column,
            operator_name,
            r#type,
            value,
            value_type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "custom_operator")]
    CustomOperator,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::CustomOperator
    }
}
