/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataSchemaCapabilities {
    #[serde(rename = "column_nullability", skip_serializing_if = "Option::is_none")]
    pub column_nullability: Option<crate::ColumnNullability>,
    /// Whether tables can have foreign keys
    #[serde(
        rename = "supports_foreign_keys",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_foreign_keys: Option<bool>,
    /// Whether tables can have primary keys
    #[serde(
        rename = "supports_primary_keys",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_primary_keys: Option<bool>,
    #[serde(
        rename = "supports_schemaless_tables",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_schemaless_tables: Option<bool>,
}

impl DataSchemaCapabilities {
    pub fn new() -> DataSchemaCapabilities {
        DataSchemaCapabilities {
            column_nullability: None,
            supports_foreign_keys: None,
            supports_primary_keys: None,
            supports_schemaless_tables: None,
        }
    }
}
