/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DefaultValueGenerationStrategy {
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl DefaultValueGenerationStrategy {
    pub fn new(r#type: RHashType) -> DefaultValueGenerationStrategy {
        DefaultValueGenerationStrategy { r#type }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "default_value")]
    DefaultValue,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::DefaultValue
    }
}
