/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

///
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ErrorResponseType {
    #[serde(rename = "uncaught-error")]
    UncaughtError,
    #[serde(rename = "mutation-constraint-violation")]
    MutationConstraintViolation,
    #[serde(rename = "mutation-permission-check-failure")]
    MutationPermissionCheckFailure,
}

impl ToString for ErrorResponseType {
    fn to_string(&self) -> String {
        match self {
            Self::UncaughtError => String::from("uncaught-error"),
            Self::MutationConstraintViolation => String::from("mutation-constraint-violation"),
            Self::MutationPermissionCheckFailure => {
                String::from("mutation-permission-check-failure")
            }
        }
    }
}

impl Default for ErrorResponseType {
    fn default() -> ErrorResponseType {
        Self::UncaughtError
    }
}
