/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ExplainResponse {
    /// Lines of the formatted explain plan response
    #[serde(rename = "lines")]
    pub lines: Vec<String>,
    /// The generated query - i.e. SQL for a relational DB
    #[serde(rename = "query")]
    pub query: String,
}

impl ExplainResponse {
    pub fn new(lines: Vec<String>, query: String) -> ExplainResponse {
        ExplainResponse { lines, query }
    }
}
