/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

///
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GraphQlType {
    #[serde(rename = "Int")]
    Int,
    #[serde(rename = "Float")]
    Float,
    #[serde(rename = "String")]
    String,
    #[serde(rename = "Boolean")]
    Boolean,
    #[serde(rename = "ID")]
    Id,
}

impl ToString for GraphQlType {
    fn to_string(&self) -> String {
        match self {
            Self::Int => String::from("Int"),
            Self::Float => String::from("Float"),
            Self::String => String::from("String"),
            Self::Boolean => String::from("Boolean"),
            Self::Id => String::from("ID"),
        }
    }
}

impl Default for GraphQlType {
    fn default() -> GraphQlType {
        Self::Int
    }
}
