/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum InsertFieldSchema {
    #[serde(rename = "array_relation")]
    ArrayRelation {
        /// The name of the array relationship over which the related rows must be inserted
        #[serde(rename = "relationship")]
        relationship: String,
    },
    #[serde(rename = "column")]
    Column {
        /// The name of the column that this field should be inserted into
        #[serde(rename = "column")]
        column: String,
        #[serde(rename = "column_type")]
        column_type: String,
        /// Is the column nullable
        #[serde(rename = "nullable")]
        nullable: bool,
        #[serde(rename = "value_generated", skip_serializing_if = "Option::is_none")]
        value_generated: Option<Box<crate::ColumnValueGenerationStrategy>>,
    },
    #[serde(rename = "object_relation")]
    ObjectRelation {
        #[serde(rename = "insertion_order")]
        insertion_order: crate::ObjectRelationInsertionOrder,
        /// The name of the object relationship over which the related row must be inserted
        #[serde(rename = "relationship")]
        relationship: String,
    },
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "column")]
    Column,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Column
    }
}
