/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct InsertCapabilities {
    /// Whether or not nested inserts to related tables are supported
    #[serde(
        rename = "supports_nested_inserts",
        skip_serializing_if = "Option::is_none"
    )]
    pub supports_nested_inserts: Option<bool>,
}

impl InsertCapabilities {
    pub fn new() -> InsertCapabilities {
        InsertCapabilities {
            supports_nested_inserts: None,
        }
    }
}
