/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MutationResponse {
    /// The results of each mutation operation, in the same order as they were received
    #[serde(rename = "operation_results")]
    pub operation_results: Vec<crate::MutationOperationResults>,
}

impl MutationResponse {
    pub fn new(operation_results: Vec<crate::MutationOperationResults>) -> MutationResponse {
        MutationResponse { operation_results }
    }
}
