/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct NestedObjectField {
    #[serde(rename = "column")]
    pub column: String,
    #[serde(rename = "query")]
    pub query: Box<crate::Query>,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl NestedObjectField {
    pub fn new(column: String, query: crate::Query, r#type: RHashType) -> NestedObjectField {
        NestedObjectField {
            column,
            query: Box::new(query),
            r#type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "object")]
    Object,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Object
    }
}
