/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

///
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ObjectRelationInsertionOrder {
    #[serde(rename = "before_parent")]
    BeforeParent,
    #[serde(rename = "after_parent")]
    AfterParent,
}

impl ToString for ObjectRelationInsertionOrder {
    fn to_string(&self) -> String {
        match self {
            Self::BeforeParent => String::from("before_parent"),
            Self::AfterParent => String::from("after_parent"),
        }
    }
}

impl Default for ObjectRelationInsertionOrder {
    fn default() -> ObjectRelationInsertionOrder {
        Self::BeforeParent
    }
}
