/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OpenApiExternalDocumentation {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "url")]
    pub url: String,
}

impl OpenApiExternalDocumentation {
    pub fn new(url: String) -> OpenApiExternalDocumentation {
        OpenApiExternalDocumentation {
            description: None,
            url,
        }
    }
}
