/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OrExpression {
    #[serde(rename = "expressions")]
    pub expressions: Vec<crate::Expression>,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl OrExpression {
    pub fn new(expressions: Vec<crate::Expression>, r#type: RHashType) -> OrExpression {
        OrExpression {
            expressions,
            r#type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "or")]
    Or,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Or
    }
}
