/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

///
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderDirection {
    #[serde(rename = "asc")]
    Asc,
    #[serde(rename = "desc")]
    Desc,
}

impl ToString for OrderDirection {
    fn to_string(&self) -> String {
        match self {
            Self::Asc => String::from("asc"),
            Self::Desc => String::from("desc"),
        }
    }
}

impl Default for OrderDirection {
    fn default() -> OrderDirection {
        Self::Asc
    }
}
