/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

use crate::comparison_column::ColumnSelector;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OrderByTarget {
    #[serde(rename = "column")]
    Column {
        #[serde(rename = "column")]
        column: ColumnSelector,
    },
    #[serde(rename = "single_column_aggregate")]
    SingleColumnAggregate {
        /// The column to apply the aggregation function to
        #[serde(rename = "column")]
        column: String,
        /// Single column aggregate function name. A valid GraphQL name
        #[serde(rename = "function")]
        function: String,
        #[serde(rename = "result_type")]
        result_type: String,
    },
    #[serde(rename = "star_count_aggregate")]
    StarCountAggregate {},
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "column")]
    Column,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Column
    }
}
