/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderByElement {
    #[serde(rename = "order_direction")]
    pub order_direction: crate::OrderDirection,
    #[serde(rename = "target")]
    pub target: crate::OrderByTarget,
    /// The relationship path from the current query table to the table that contains the target to order by. This is always non-empty for aggregate order by targets
    #[serde(rename = "target_path")]
    pub target_path: Vec<String>,
}

impl OrderByElement {
    pub fn new(
        order_direction: crate::OrderDirection,
        target: crate::OrderByTarget,
        target_path: Vec<String>,
    ) -> OrderByElement {
        OrderByElement {
            order_direction,
            target,
            target_path,
        }
    }
}
