/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct QueryCapabilities {
    #[serde(
        rename = "foreach",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub foreach: Option<Option<serde_json::Value>>,
}

impl QueryCapabilities {
    pub fn new() -> QueryCapabilities {
        QueryCapabilities {
            foreach: Some(Some(serde_json::json!({}))),
        }
    }
}
