/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use std::collections::BTreeMap;

use crate::target::target_or_table_name;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryRequest {
    /// If present, a list of columns and values for the columns that the query must be repeated for, applying the column values as a filter for each query.
    #[serde(
        rename = "foreach",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub foreach: Option<Option<Vec<::std::collections::HashMap<String, crate::ScalarValue>>>>,

    #[serde(rename = "query")]
    pub query: Box<crate::Query>,

    /// The target of the query.
    /// For backwards compatibility with previous versions of dc-api we allow the alternative property name "table" and allow table names to be parsed into Target::TTable
    #[serde(
        rename = "target",
        alias = "table",
        deserialize_with = "target_or_table_name"
    )]
    pub target: crate::Target,

    /// The relationships between tables involved in the entire query request
    #[serde(rename = "relationships", alias = "table_relationships")]
    pub relationships: Vec<crate::TableRelationships>,

    /// This field is not part of the v2 DC Agent API - it is included to support queries
    /// translated from the v3 NDC API. A query request may include either `foreach` or
    /// `variables`, but should not include both.
    #[serde(skip)]
    pub variables: Option<Vec<VariableSet>>,
}

pub type VariableSet = BTreeMap<String, serde_json::Value>;

impl QueryRequest {
    pub fn new(
        query: crate::Query,
        target: crate::Target,
        relationships: Vec<crate::TableRelationships>,
    ) -> QueryRequest {
        QueryRequest {
            foreach: None,
            query: Box::new(query),
            target,
            relationships,
            variables: None,
        }
    }
}
