/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use ::std::collections::HashMap;

use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum QueryResponse {
    /// In a foreach query we respond with multiple result sets, one for each foreach predicate.
    /// This variant uses a struct constructor to reflect the API JSON format.
    ForEach { rows: Vec<ForEachRow> },
    /// In a non-foreach query we respond with a single result set.
    /// This variant uses a tuple constructor to reflect the lack of a wrapping object in the API
    /// JSON format.
    Single(RowSet),
}

impl QueryResponse {
    pub fn new() -> QueryResponse {
        QueryResponse::Single(Default::default())
    }
}

impl Default for QueryResponse {
    fn default() -> Self {
        Self::new()
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ForEachRow {
    pub query: RowSet,
}

/// A row set must contain either rows, or aggregates, or possibly both
#[skip_serializing_none]
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RowSet {
    Aggregate {
        /// The results of the aggregates returned by the query
        aggregates: HashMap<String, serde_json::Value>,
        /// The rows returned by the query, corresponding to the query's fields
        rows: Option<Vec<HashMap<String, ResponseFieldValue>>>,
    },
    Rows {
        /// Rows returned by a query that did not request aggregates.
        rows: Vec<HashMap<String, ResponseFieldValue>>,
    },
}

impl Default for RowSet {
    fn default() -> Self {
        RowSet::Rows {
            rows: Default::default(),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ResponseFieldValue {
    Relationship(Box<RowSet>),
    Column(serde_json::Value),
}
