/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RawRequest {
    /// A string representing a raw query
    #[serde(rename = "query")]
    pub query: String,
}

impl RawRequest {
    pub fn new(query: String) -> RawRequest {
        RawRequest { query }
    }
}
