/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelationshipField {
    #[serde(rename = "query")]
    pub query: Box<crate::Query>,
    /// The name of the relationship to follow for the subquery
    #[serde(rename = "relationship")]
    pub relationship: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl RelationshipField {
    pub fn new(query: crate::Query, relationship: String, r#type: RHashType) -> RelationshipField {
        RelationshipField {
            query: Box::new(query),
            relationship,
            r#type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "relationship")]
    Relationship,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Relationship
    }
}
