/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RelatedTable {
    #[serde(rename = "relationship")]
    pub relationship: String,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl RelatedTable {
    pub fn new(relationship: String, r#type: RHashType) -> RelatedTable {
        RelatedTable {
            relationship,
            r#type,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "related")]
    Related,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Related
    }
}
