/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum RowUpdate {
    #[serde(rename = "custom_operator")]
    CustomUpdateColumnOperatorRowUpdate {
        /// The name of the column in the row
        #[serde(rename = "column")]
        column: String,
        #[serde(rename = "operator_name")]
        operator_name: String,
        /// The value to use with the column operator
        #[serde(rename = "value")]
        value: ::std::collections::HashMap<String, serde_json::Value>,
        #[serde(rename = "value_type")]
        value_type: String,
    },
    #[serde(rename = "set")]
    SetColumnRowUpdate {
        /// The name of the column in the row
        #[serde(rename = "column")]
        column: String,
        /// The value to use with the column operator
        #[serde(rename = "value")]
        value: ::std::collections::HashMap<String, serde_json::Value>,
        #[serde(rename = "value_type")]
        value_type: String,
    },
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "set")]
    Set,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Set
    }
}
