/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StarCountAggregate {
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl StarCountAggregate {
    pub fn new(r#type: RHashType) -> StarCountAggregate {
        StarCountAggregate { r#type }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "star_count")]
    StarCount,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::StarCount
    }
}
