/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubqueryComparisonCapabilities {
    /// Does the agent support comparisons that involve related tables (ie. joins)?
    #[serde(rename = "supports_relations", skip_serializing_if = "Option::is_none")]
    pub supports_relations: Option<bool>,
}

impl SubqueryComparisonCapabilities {
    pub fn new() -> SubqueryComparisonCapabilities {
        SubqueryComparisonCapabilities {
            supports_relations: None,
        }
    }
}
