/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

///
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TableType {
    #[serde(rename = "table")]
    Table,
    #[serde(rename = "view")]
    View,
}

impl ToString for TableType {
    fn to_string(&self) -> String {
        match self {
            Self::Table => String::from("table"),
            Self::View => String::from("view"),
        }
    }
}

impl Default for TableType {
    fn default() -> TableType {
        Self::Table
    }
}
