/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UniqueIdentifierGenerationStrategy {
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl UniqueIdentifierGenerationStrategy {
    pub fn new(r#type: RHashType) -> UniqueIdentifierGenerationStrategy {
        UniqueIdentifierGenerationStrategy { r#type }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "unique_identifier")]
    UniqueIdentifier,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::UniqueIdentifier
    }
}
