/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UnrelatedTable {
    /// The fully qualified name of a table, where the last item in the array is the table name and any earlier items represent the namespacing of the table name
    #[serde(rename = "table")]
    pub table: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: RHashType,
}

impl UnrelatedTable {
    pub fn new(table: Vec<String>, r#type: RHashType) -> UnrelatedTable {
        UnrelatedTable { table, r#type }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "unrelated")]
    Unrelated,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Unrelated
    }
}
