/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateColumnOperatorDefinition {
    #[serde(rename = "argument_type")]
    pub argument_type: String,
}

impl UpdateColumnOperatorDefinition {
    pub fn new(argument_type: String) -> UpdateColumnOperatorDefinition {
        UpdateColumnOperatorDefinition { argument_type }
    }
}
