/*
 *
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document:
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateMutationOperation {
    #[serde(rename = "post_update_check", skip_serializing_if = "Option::is_none")]
    pub post_update_check: Option<Box<crate::Expression>>,
    /// The fields to return for the rows affected by this update operation
    #[serde(
        rename = "returning_fields",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub returning_fields: Option<Option<::std::collections::HashMap<String, crate::Field>>>,
    /// The fully qualified name of a table, where the last item in the array is the table name and any earlier items represent the namespacing of the table name
    #[serde(rename = "table")]
    pub table: Vec<String>,
    #[serde(rename = "type")]
    pub r#type: RHashType,
    /// The updates to make to the matched rows in the table
    #[serde(rename = "updates")]
    pub updates: Vec<crate::RowUpdate>,
    #[serde(rename = "where", skip_serializing_if = "Option::is_none")]
    pub r#where: Option<Box<crate::Expression>>,
}

impl UpdateMutationOperation {
    pub fn new(
        table: Vec<String>,
        r#type: RHashType,
        updates: Vec<crate::RowUpdate>,
    ) -> UpdateMutationOperation {
        UpdateMutationOperation {
            post_update_check: None,
            returning_fields: None,
            table,
            r#type,
            updates,
            r#where: None,
        }
    }
}

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "update")]
    Update,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Update
    }
}
