name: Tests

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Nix ❄
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Link Cachix 🔌
        uses: cachix/cachix-action@v12
        with:
          name: '${{ vars.CACHIX_CACHE_NAME }}'
          authToken: '${{ secrets.CACHIX_CACHE_AUTH_TOKEN }}'

      - name: run unit tests 🔨
        run: nix build .#checks.x86_64-linux.test --print-build-logs

      - name: run linter checks with clippy 🔨
        run: nix build .#checks.x86_64-linux.lint --print-build-logs

      - name: run integration tests 📋
        run: nix develop --command just test-mongodb-versions

      - name: run relational integration tests 📋
        run: nix develop --command just test-relational-mongodb-versions

  audit:
    name: Security Audit
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install Nix ❄
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Link Cachix 🔌
        uses: cachix/cachix-action@v12
        with:
          name: '${{ vars.CACHIX_CACHE_NAME }}'
          authToken: '${{ secrets.CACHIX_CACHE_AUTH_TOKEN }}'

      - name: audit for reported security problems 🔨
        run: nix develop --command cargo audit
